### ISSUE TITLE
Implement cross-site-scripting protection

### ISSUE THREAD

**Issue by simon-brooke** [simon-brooke/smeagol#21]
Smeagol doesn't currently have anti-forgery protection. It should have.

**Comment by desolate-planet** [comment]
Does this seem like a reasonable lib to make use of: https://github.com/ring-clojure/ring-anti-forgery?

**Comment by simon-brooke** [comment]
That's the right one, yes. Thanks!

**Comment by simon-brooke** [comment]
Fixed.
